### ISSUE TITLE
Do not disable transparent hugepages

### ISSUE THREAD

**Issue by wolf31o2** [RiotGamesCookbooks/cloudera-cookbook#7]
Instead, disable compaction, as suggested by Cloudera:

echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag

**Comment by wolf31o2** [comment]
Also, this needs to be templated... I suggest wrapping it around platform_family/platform_version.to_i 6...

**Comment by l1x** [comment]
Hey Chris,

Could you submit pull requests for these?

**Comment by wolf31o2** [comment]
Sure.  You want me to fork and make the modifications, then?

**Comment by l1x** [comment]
For, make the changes and submit a pull request please. Thank you in advance.

**Comment by wolf31o2** [comment]
Cool... Will do as soon as I get a chance, which will hopefully be this week... thanks!

**Comment by wolf31o2** [comment]
OK... This is in issue #9 now...
